# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/indian-super-league',
                'doc_host': 'https://football-kowshik.github.io',
                'git_url': 'https://github.com/football-kowshik/indian-super-league',
                'lib_path': 'indian_super_league'},
  'syms': { 'indian_super_league.core': {'indian_super_league.core.foo': ('core.html#foo', 'indian_super_league/core.py')},
            'indian_super_league.matches': {}}}
