# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_constants.ipynb.

# %% auto 0
__all__ = ['log_dir', 'data_dir', 'sample_match_id']

# %% ../nbs/00_constants.ipynb 3
import warnings
warnings.filterwarnings('ignore')

import datetime
import json
import logging
import os
from pathlib import Path

import pandas as pd

# %% ../nbs/00_constants.ipynb 5
#| eval: false
#| output: false
log_dir = Path('../logs')
if not os.path.exists(log_dir):
    os.makedirs(log_dir, exist_ok=True)

data_dir = Path('../data')
if not os.path.exists(data_dir):
    os.makedirs(data_dir, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename=os.path.join(log_dir, 'isl.log'),
    filemode='a'
)

# %% ../nbs/00_constants.ipynb 6
#| eval: false
#| output: false
sample_match_id = 68105
