"""Data about ISL matches."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_matches.ipynb.

# %% auto 0
__all__ = ['log_dir', 'data_dir']

# %% ../nbs/01_matches.ipynb 3
import warnings
warnings.filterwarnings('ignore')

import json
import logging
import os
from pathlib import Path

import requests

# %% ../nbs/01_matches.ipynb 5
log_dir = Path('../logs')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

data_dir = Path('../data')
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename=os.path.join(log_dir, 'matches.log'),
    filemode='a'
)
