"""Data about matches."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_matches.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_matches.ipynb 2
import warnings
warnings.filterwarnings('ignore')

import json
import logging
import os
import requests
